---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local 
  tasks:
    - name: install tmux
      homebrew: name=tmux state=present

    - name: copy .gitconfig
      copy: src=./dotfiles/.gitconfig dest=~/

    - name: copy .tmux.conf
      copy: src=./dotfiles/.tmux.conf dest=~/

    - name: copy .vimrc
      copy: src=./dotfiles/.vimrc dest=~/

    - name: copy .bashrc
      copy: src=./dotfiles/.bashrc dest=~/

    - name: copy .bash_profile
      copy: src=./dotfiles/.bash_profile dest=~/

    - name: clone vim vundle
      git: repo=https://github.com/gmarik/vundle.git  dest=~/.vim/vundle.git accept_hostkey=yes 

    - name: download color scheme
      git: repo=https://github.com/waysaku/molokai.git dest=~/git/molokai

    - name: copy color scheme 
      copy: src=~/git/molokai/colors/molokai.vim dest=~/.vim/colors/

    - name: clone git repository
      git: repo=https://github.com/git/git.git dest=~/git/git

    - name: copy git-completion.bash 
      copy: src=~/git/git/contrib/completion/git-completion.bash dest=/usr/local/git/contrib/completion/

    - name: copy git-prompt.sh
      copy: src=~/git/git/contrib/completion/git-prompt.sh dest=/usr/local/git/contrib/completion/
