---
- hosts: 127.0.0.1
  gather_facts: yes
  connection: local 
  tasks:
    - import_tasks: setups/setup-ubuntu.yaml
      when: ansible_os_family == 'Debian'

    - import_tasks: setups/setup-mac.yaml
      when: ansible_os_family == 'Darwin'
