---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local 
  tasks:
    - name: install tmux
      homebrew: name=tmux state=present

    - name: install reattach-to-user-namespace
      homebrew: name=reattach-to-user-namespace state=present

    - name: copy .gitconfig
      copy: src=./dotfiles/.gitconfig dest=~/

    - name: copy .tmux.conf
      copy: src=./dotfiles/.tmux.conf dest=~/

    - name: copy .vimrc
      copy: src=./dotfiles/.vimrc dest=~/

    - name: copy .bashrc
      copy: src=./dotfiles/.bashrc dest=~/

    - name: copy .bash_profile
      copy: src=./dotfiles/.bash_profile dest=~/

    - name: clone vim neovundle
      git: repo=https://github.com/Shougo/neobundle.vim  dest=~/.vim/bundle/neobundle.vim accept_hostkey=yes 

    - name: download color scheme
      git: repo=https://github.com/waysaku/molokai.git dest=~/git/molokai

    - name: copy color scheme 
      copy: src=~/git/molokai/colors/molokai.vim dest=~/.vim/colors/

    - name: install nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
    
    - name: install nodejs on nvm
      shell: source ~/.bashrc && nvm install v0.12.7 && nvm use v0.12.7

    - name: copy git-completion.bash 
      copy: src=./git-bashfiles/git-completion.bash dest=/usr/local/git/contrib/completion/

    - name: copy git-prompt.sh
      copy: src=./git-bashfiles/git-prompt.sh dest=/usr/local/git/contrib/completion/
