---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local 
  tasks:
    - name: install tmux
      homebrew: name=tmux state=present

    - name: install reattach-to-user-namespace
      homebrew: name=reattach-to-user-namespace state=present

    - name: brew tap for installing Ricty font
      homebrew_tap:
        name: sanemat/font

    - name: install Ricty font
      homebrew: name=ricty state=present

    - name: finish installing Ricty font
      shell: cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/ && fc-cache -vf

    - name: copy .gitconfig
      copy: src=./dotfiles/.gitconfig dest=~/

    - name: copy .tmux.conf
      copy: src=./dotfiles/.tmux.conf dest=~/

    - name: copy .vimrc
      copy: src=./dotfiles/.vimrc dest=~/

    - name: copy .bashrc
      copy: src=./dotfiles/.bashrc dest=~/

    - name: copy .bash_profile
      copy: src=./dotfiles/.bash_profile dest=~/

    - name: copy .editorconfig
      copy: src=./dotfiles/.editorconfig dest=~/

    - name: clone vim neovundle
      git: repo=https://github.com/Shougo/neobundle.vim  dest=~/.vim/bundle/neobundle.vim accept_hostkey=yes 

    - name: download color scheme
      git: repo=https://github.com/waysaku/vim dest=~/git/vim

    - name: copy color scheme 
      copy: src=~/git/vim/colors/dracula.vim dest=~/.vim/colors/

    - name: install nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
      args:
        warn: False
    
    - name: copy git-completion.bash 
      copy: src=./git-bashfiles/git-completion.bash dest=/usr/local/git/contrib/completion/

    - name: copy git-prompt.sh
      copy: src=./git-bashfiles/git-prompt.sh dest=/usr/local/git/contrib/completion/

    - name: install nodejs on nvm
      shell: source ~/.bashrc && nvm install v10.15.0 && nvm use v10.15.0


